#! /usr/bin/env bash

source $(dirname $0)/commonHeader.sh

### ==================================================================
### ================  LOCAL FUNCTION PART   ==========================
###
usage() {
        echo "usage: $MYNAME hostlist from_n to_n"
        [ $ARGS -lt 3 ] && echo "(too few arguments)" \
        || echo "(too many arguments)"
}


###
### ================ END LOCAL FUNCTION PART   =======================
### ==================================================================

### ==================================================================
### ================         BODY        =============================


HOSTLIST=$1; INDX_T=$2; INDX_B=$3

RMT_AGNT1=$REMOTE_AGENT1
REPORTDIR=$REPORT_DIR
AUTH_PREF=$AUTHORIZATION_FILE_DIR
declare -a HOSTS
declare -a AFILES

printInfo "started $*"
[ $ARGS -ne 3 ] && usage && exitOK

[ ! -d $REPORTDIR ] && mkdir -p $REPORTDIR
[ ! -d $REPORTDIR ] && printErr "can't create $REPORTDIR" && exitOK


### read server list
### echo "line:: $authFile $host"
i=0
while IFS=$' \t' read HOSTS[$i] AFILES[$i]
do (( i++ )); done < <(sed -n "$INDX_T, $INDX_B p" "$HOSTLIST")

i=0
ALNG=$(( ${#HOSTS[@]} - 1 ))
while [ $i -lt $ALNG ]
do
	echo "======================="
	authFile=${AFILES[$i]}
	host=${HOSTS[$i]}
	echo "agnt for host: $host $authFile"
	(( i++ ))
	
	### ditribute and start Agnt
	scp -i /$AUTH_PREF/$authFile $RMT_AGNT1 $host:/tmp
	ssh -i /$AUTH_PREF/$authFile $host \
	"echo -e '$(date) \c'; echo on \$(hostname) starting $RMT_AGNT1; /tmp/$RMT_AGNT1" \
	< /dev/null
	echo "$(date) $RMT_AGNT1 done"
	echo "-----------------------"
	echo "$(date) fetch reports from $host"
	### for each listed server instance
	### fetch the fruits
	scp -i /$AUTH_PREF/$authFile $host:/tmp/*.pckgList* $REPORTDIR
	ssh -i /$AUTH_PREF/$authFile $host "rm /tmp/*.pckgList*" \
	< /dev/null
done
echo "-----------------------"
DONE=1
