#! /usr/bin/env bash

source $(dirname $0)/commonHeader.sh

### ==================================================================
### ================  LOCAL FUNCTION PART   ==========================
###
usage() {
        echo "usage: $MYNAME hostlist from_n to_n"
        [ $ARGS -lt 3 ] && echo "(too few arguments)" \
        || echo "(too many arguments)"
}


###
### ================ END LOCAL FUNCTION PART   =======================
### ==================================================================

### ==================================================================
### ================         BODY        =============================


HOSTLIST=$1; INDX_T=$2; INDX_B=$3

RMT_AGNT1=$REMOTE_AGENT1
REPORTDIR=$REPORT_DIR
AUTH_PREF=$AUTHORIZATION_FILE_DIR
declare -a HOSTS
declare -a AFILES

printInfo "started $*"
[ $ARGS -ne 3 ] && usage && exitOK

[ ! -d $REPORTDIR ] && mkdir -p $REPORTDIR
[ ! -d $REPORTDIR ] && printErr "can't create $REPORTDIR" && exitOK


### read server list
### line format: $host $authFile 
i=0
### load wrk list into HOSTS/AFILES array
while IFS=$' \t' read HOSTS[$i] AFILES[$i]
do X=$(( i++ )); done \
<<<"$(sed -n "$INDX_T, $INDX_B p" "$HOSTLIST")"

### spin the job for each host in HOSTS array
i=0
LISTLNG=$(( ${#HOSTS[@]} - 1 ))
while [ $i -lt $LISTLNG ]
do
	### i.e. for particular host (server) do following
	authFile=${AFILES[$i]}
	host=${HOSTS[$i]}
	printInfo "agnt for host: $host, $authFile"
	X=$(( i++ ))
	
	### create tmp dir for expected reports 
	### created on remote server
	TMPREPDIR="$REPORTDIR/tmp-$host"
	[ -d $TMPREPDIR ] && rm -r $TMPREPDIR
	[ -d $TMPREPDIR ] && printErr "can't rm $TMPREPDIR" && exitOK
	mkdir $TMPREPDIR
	[ ! -d $TMPREPDIR ] && printErr "can't create $TMPREPDIR" && exitOK

	### check accessibility
	PINGMAX=5
	i=0
	while [ $((i++)) -le $PINGMAX ]
	do
		/bin/ping -c $i $host >/dev/null 2>&1 && RETV=1 || RETV=0
		[ $RETV -eq 1 ] && break
		
	done
	[ $RETV -eq 0 ] && MSG="ERROR:" || MSG="INFO:"
	echo "$MSG $host $i, indx: $INDX_T, $INDX_B" >> /tmp/allPong.log
	[ $RETV -eq 0 ] && echo $host > $MARKER_DIR/$host.noPing
	[ $RETV -eq 0 ] && printErr "unknown host route to: $host" && exitOK
	printInfo "route ok: $host $i, indx: $INDX_T, $INDX_B"


	### distribute and start Agnt on remote host

	[ "$authFile" = "N/A" ] && AUTH_OPT="" \
	|| AUTH_OPT="-i /$AUTH_PREF/$authFile"

	### make sure you know later the hostname
	[ -f $MARKER_DIR/$host.$MARKER_SUF ] && rm [ -f $MARKER_DIR/$host.$MARKER_SUF ]
	MARKER=$($SSH_NOKEY $AUTH_OPT $ZXUSER@$host "hostname" 2>/dev/null)
	[ ! -z "$MARKER" ] && OK=1 || OK=0
	[ $OK -eq 1 ] && echo $MARKER > $MARKER_DIR/$host.$MARKER_SUF
	[ $OK -eq 0 ] && echo $host > $MARKER_DIR/$host.noName
	[ $OK -eq 0 ] && printErr "catch MARKER from $host" && exitOK

done
DONE=1
