#! /usr/bin/env bash

source $(dirname $0)/commonHeader.sh

### ==================================================================
### ================  LOCAL FUNCTION PART   ==========================
###
usage() {
        echo "usage: $MYNAME hostlist from_n to_n"
        [ $ARGS -lt 3 ] && echo "(too few arguments)" \
        || echo "(too many arguments)"
}


###
### ================ END LOCAL FUNCTION PART   =======================
### ==================================================================

### ==================================================================
### ================         BODY        =============================


HOSTLIST=$1; INDX_T=$2; INDX_B=$3

RMT_AGNT1=$REMOTE_AGENT1
REPORTDIR=$REPORT_DIR
AUTH_PREF=$AUTHORIZATION_FILE_DIR
declare -a HOSTS
declare -a AFILES

printInfo "started $*"
[ $ARGS -ne 3 ] && usage && exitOK

[ ! -d $REPORTDIR ] && mkdir -p $REPORTDIR
[ ! -d $REPORTDIR ] && printErr "can't create $REPORTDIR" && exitOK


### read server list
### line format: $host $authFile 
i=0
### load wrk list into HOSTS/AFILES array
while IFS=$' \t' read HOSTS[$i] AFILES[$i]
do X=$(( i++ )); done \
<<<"$(sed -n "$INDX_T, $INDX_B p" "$HOSTLIST")"

### spin the job for each host in HOSTS array
i=0
ALNG=$(( ${#HOSTS[@]} - 1 ))
while [ $i -lt $ALNG ]
do
	### i.e. for particular host (server) do following
	echo "======================="
	authFile=${AFILES[$i]}
	host=${HOSTS[$i]}
	echo "agnt for host: $host $authFile"
	X=$(( i++ ))
	
	### create tmp dir for expected reports 
	### created on remote server
	TMPREPDIR="$REPORTDIR/tmp-$host"
	[ -d $TMPREPDIR ] && rm -r $TMPREPDIR
	[ -d $TMPREPDIR ] && printErr "can't rm $TMPREPDIR" && exitOK
	mkdir $TMPREPDIR
	[ ! -d $TMPREPDIR ] && printErr "can't create $TMPREPDIR" && exitOK

	### check name resolution
	nslookup $host.1>/dev/null 2>&1 && RETV=1 || RETV=0
	[ $RETV -eq 0 ] printErr "uknown host: $host" && exitOK

	### distribute and start Agnt on remote host

	[ "$authFile" = "N/A" ] && AUTH_OPT="" \
	|| AUTH_OPT="-i /$AUTH_PREF/$authFile"
	### make sure you know later the hostname
	MARKER=$(ssh $AUTH_OPT $host "hostname" < /dev/null)
	echo $MARKER > $MARKER_DIR/$host.$MARKER_SUF
	### copy script from here to the remote host
	scp $AUTH_OPT $RMT_AGNT1 $host:/tmp
	### start execution on remote host
	ssh $AUTH_OPT $host \
	"echo -e '$(date) \c'; echo on \$(hostname) starting $RMT_AGNT1; /tmp/$RMT_AGNT1" \
	< /dev/null
	echo "$(date) $RMT_AGNT1 done"
	echo "-----------------------"
	echo "$(date) fetch reports from $host"
	### fetch the reports from remote server in to local tmp storage
	scp $AUTH_OPT $host:/tmp/*.pckgList* $TMPREPDIR && SCP=1 || SCP=0
	### clean up remote server
	ssh $AUTH_OPT $host "rm /tmp/*.pckgList*" 
	### if everything went good mv report files in to final destination place
	[ $SCP -eq 1 ] && mv $TMPREPDIR/* $REPORTDIR && rmdir $TMPREPDIR || SCP=0
	[ $SCP -eq 0 ] && printErr "scp failed" && exitOK
	< /dev/null
done
echo "-----------------------"
DONE=1
